[package]
name = "student_virus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.7.0"
walkdir = "2.5.0"
glob = "0.3.1"
rand = "0.9.0-alpha.0"
