[package]
name = "student_virus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.7.0"
walkdir = "2.5.0"
glob = "0.3.1"
rand = "0.9.0-alpha.0"
clap = { version = "4.5.1", features = ["derive"] }
sys-info = "0.9.1"
async-walkdir = "1.0.0"
